# Generated by Django 3.2.5 on 2022-01-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_creator', models.CharField(max_length=200)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_details', models.CharField(max_length=200)),
                ('blog_content', models.TextField()),
                ('blog_tags', models.CharField(max_length=200)),
                ('blog_responses', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TagData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('tag', models.ManyToManyField(blank=True, to='blog.Blog')),
            ],
        ),
    ]
