# Generated by Django 3.2.5 on 2021-12-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('blogcontent', models.CharField(max_length=20000)),
                ('tags', models.CharField(max_length=200)),
                ('responses', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TagData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
    ]
