# Generated by Django 3.2.5 on 2022-01-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.CharField(max_length=10000),
        ),
    ]
