# Generated by Django 3.2.5 on 2022-01-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_content',
        ),
    ]
